### ISSUE TITLE
Mixxx portaudio USE flag dependencies

### ISSUE THREAD

**Issue by simonvanderveldt** [dguglielmi/sunny-overlay#1]
Hi David,

Just installed Mixxx from your overlay (thanks!) and ran into a "small" issue that it didn't have any  options in the "Sound API" dropdown :P

This was caused by `portaudio` which I had emerged without any sound backend USE flags set.

Shouldn't the emerge of Mixxx error because at least one of alsa, jack or oss needs to be set for portaudio?
Or are there cases where one wouldn't need at least one of them?

**Comment by dguglielmi** [comment]
Hi,

Thank for the report.

I will see that.
