### ISSUE TITLE
issue with goodix device 

### ISSUE THREAD

**Issue by koles-ya** [dguglielmi/sunny-overlay#2]
trying to make goodix (27c6:5385) device work on gentoo. 
1. cant build fprintd from your overlay because of https://bugs.gentoo.org/737468
2. building edited fprintd ebuild without pam_wrapper doesn't see the device.
any ideas?

**Comment by dguglielmi** [comment]
Unfortunaly no, but 27c6:5385 is not listed in the udev rules file provided with the proprietary driver
- https://github.com/dguglielmi/sunny-overlay/blob/master/sys-auth/libfprint-tod-goodix-drivers/files/60-libfprint-2-tod1-goodix.rules

Your best luck is following this bug from libfprint

- https://gitlab.freedesktop.org/libfprint/libfprint/-/issues/43
